version: '2'
services:
  management1:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: "ndb_mgmd --ndb-nodeid=1"
    #command: ndb_mgmd
  ndb1:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    #command: bash -c 'sleep 40; exec ndbd'
    command: ndbd
    depends_on:
      - "management1"
  ndb2:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    #command: bash -c 'sleep 40; exec ndbd'
    command: ndbd
    depends_on:
      - "management1"
  mysql1:
    image: mysql/mysql-cluster
    ports:
      - "3306:3306"
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    #command: bash -c 'sleep 60; exec mysqld'
    command: mysqld
    depends_on:
      - "management1"
      - "ndb1"
      - "ndb2"
